define({
  root: {
    labelBookmarkName: "Bookmark the current view",
    labelPlay: "Play All",
    labelStop: "Stop",
    labelDelete: "Delete",
    placeholderBookmarkName: "Bookmark Name",
    errorNameExist: "Bookmark exists!",
    errorNameNull: "Invalid bookmark name!",
	ERROR_MSG_MAPSERVER_CHILD: "Indirizzo non valido! Inserire l'URL di base del servizio \"Map Server\" ",
	ERROR_MSG_UNCORRECT_URL: "URL non valido!",
	ERROR_MSG_UNCORRECT_WEBMAPID: "WebMap ID non valido!",
	ERROR_MSG_UNSUCCESSFUL_ESRI_REQUEST: "La richiesta di dati al server non è andata a buon fine.",
    GENERIC_ERROR_MSG: "Errore!",
	ArcGISServerTab: "ArcGIS Server",
    WMSServerTab: "WMS Server",
    AGOLTab: "WebMap AGOL",
    NoneFilter: "Nessun Filtro",
    MapServFilter: "MapServer",
    FeatServFilter: "FeatureServer",
    ImageServFilter: "ImageServer",
    SYS_STYLE_OPTION_1:"Stili disponibili",
    TOOL_ADDSERVICEONFLY_1: "Aggiungi Servizio",
    TOOL_ADDSERVICEONFLY_2:"Catalogo",
    TOOL_ADDSERVICEONFLY_3:"Cartelle",
    TOOL_ADDSERVICEONFLY_4:"Servizi",
    TOOL_ADDSERVICEONFLY_5:"Tiled",
    TOOL_ADDSERVICEONFLY_6:"Dynamic",
    TOOL_ADDSERVICEONFLY_7:"Inserire URL del Catalogo",
    TOOL_ADDSERVICEONFLY_8:"Vericare URL del Catalogo",
    TOOL_ADDSERVICEONFLY_9:"Catalogo non presente o Accesso non consentito!",
    TOOL_ADDSERVICEONFLY_10:"Aggiungi",
    TOOL_ADDSERVICEONFLY_11:"Seleziona una Cartella",
    TOOL_ADDSERVICEONFLY_12:"Pagina richiesta non trovata!",
    TOOL_ADDSERVICEONFLY_13:"Il server riporta un errore",
    TOOL_ADDSERVICEONFLY_14:"Necessaria autenticazione!",
    TOOL_ADDSERVICEONFLY_15:"Seleziona un Servizio",
    TOOL_ADDSERVICEONFLY_16:"Descrizione",
    TOOL_ADDSERVICEONFLY_17:"Capabilities",
    TOOL_ADDSERVICEONFLY_18:"Map Cache",
    TOOL_ADDSERVICEONFLY_19:"Spatial Reference",
    TOOL_ADDSERVICEONFLY_20:"Tipo Servizio",
    TOOL_ADDSERVICEONFLY_21:"Servizio NON utilizzabile OnFly!",
    TOOL_ADDSERVICEONFLY_22:"WMS",
    TOOL_ADDSERVICEONFLY_23:"Inserire URL del Servizio",
    TOOL_ADDSERVICEONFLY_24:"URL del Servizio",
    TOOL_ADDSERVICEONFLY_25:"Filtro sul Tipo di Servizio",
    TOOL_ADDSERVICEONFLY_26:"Controllare URL del servizio e Tipo Servizio!!!",
    TOOL_ADDSERVICEONFLY_27:"Esri Service",
    TOOL_ADDSERVICEONFLY_28:"Si",
    TOOL_ADDSERVICEONFLY_29:"No",
    TOOL_ADDSERVICEONFLY_30:"Strati Informativi",
    TOOL_ADDSERVICEONFLY_31:"Aggiungi alla mappa multiplo",
    TOOL_ADDSERVICEONFLY_32:"ArcGIS Online WebMap ID",
    TOOL_ADDSERVICEONFLY_33:"Inserire ID della WebMap AGOL",
    TOOL_ADDSERVICEONFLY_34:"Ricerca in un catalogo",
    TOOL_ADDSERVICEONFLY_35:"Inserisci URL servizio",
    TOOL_ADDSERVICEONFLY_36:"-"
	},
  "zh-cn": true
});