define({
  root: {
    labelCatalog: "Catalog",
    selectByAttribute: "Search",
    results: "Results",
    showAll: "Show all",
    search: "Search",
    searchText: "Keywords",
    liveData: "Live Data Maps",
    clear: "Clear",
    featuresSelected: "Features found: ",
    featuresPage: "Total page(s): ",
    noResults: "No results",
    queryError:"Query failed !",
    queryResult:"Query result",
    intersecting: "Intersecting",
    within: "Within",
    anywhere: "Anywhere",
    addToMap: "Apri nel Viewer",
    preview:"Anteprima",
    details: "Metadati",
    open: "Vedi",
    website: "Sito Web",
    metadata: "Metadati-XML",
    WMS: "Link WMS",
    WFS: "Link WFS",
    WCS: "Link WCS",
    WMTS: "Link WMTS",
    imageserver: "Servizio Image",
    inspireview: "Servizio View",
    download: "Scarica",
    alertProjection:"Il servizio richiesto ha una proiezione diversa da quella attualmente utilizzate e potrebbe non essere visualizzato correttamente"
  },
  "zh-cn": true
});