define(
    ({
        label1: "I am a demo widget.",
        label2: "This is configurable.",
        labelCatalog: "Catalogo",
        selectByAttribute: "Cerca",
        results: "Risultati",
        showAll: "Mostra tutto",
        search: "Cerca",
        searchText: "Parola chiave",
        liveData: "Solo Servizi Mappa",
        clear: "Pulisci",
        footprints: "Footprints: ",
        show: "Mostra",
        hide: "Nascondi",
        featuresSelected: "Elementi trovati: ",
        noResults: "Nessun risultato",
        layerLoadError:"Non è stato possibile caricre il servizio richiesto. Verificare che il servizio sia accessibile",
        layerLoadTitle:"ERRORE",
        layerLoadDetail: "Dettaglio",
        queryError: "Siamo spiacenti, l'interrogazione non è andata a buon fine!",        
        queryResult: "L'interrogazione è andata buon fine",
        intersecting: "Interseca l'estensione corrente",
        within: "Contenuto nell'estensione corrente",
        anywhere: "Nessun filtro spaziale",
        addtomap: "Aggiungi alla mappa",

        urlFormatNotValid: "Il formato della url del servizio è errata!",
        serviceTypeNotHandled: "Tipo di servizio non gestito: ",
        details: "Scheda Metadati",
        metadata: "Metadati-XML",
        website: "Sito Web",
        preview: "Anteprima",
        open: "Accedi", // orig: Esplora
        addToMap: "Aggiungi alla Mappa",
        agskml: "Globo (.kml)",
        agsnmf: "Globo (.nmf)",
        agslyr: "Desktop GIS",
        "catalog.rest.wms": "Servizio WMS",
        "catalog.rest.wfs": "Servizio WFS",
        "catalog.rest.wcs": "Servizio WCS",
        "catalog.rest.wmts": "Servizio WMTS",
        "catalog.rest.download": "Servizio di Download"
    })
);